### ISSUE TITLE
how to use es6-module with threejs ?

### ISSUE THREAD

**Issue by Ge-yuan-jun** [learnthreejs/three-js-boilerplate#1]
After watching your video, I'm wondering if you are interesting in using es6 code with three.js.

I only find how to import three.js NPM package. but, it seems that it's difficult to import OBJLoader .

any idea?

**Comment by Here2Huynh** [comment]
I am getting the same issue as well. Any ideas to get around it?

**Comment by Fouzyyyy** [comment]
@Ge-yuan-jun @Here2Huynh  I use this syntax: `import 'three/examples/js/loaders/OBJLoader'` to import obj loader, but this loader as the rest supposes that the three.js library is declared globally, so to use the three.js as an npm package and make it available globally I do this:
`import * as THREE from 'three';` and then:  `window.THREE = THREE;`

**Comment by tristangemus** [comment]
Closing as this is for issues with this repository.
